Supression
angrymeir/SecScanner2JUnit pull request #20
Opened 2022-08-10 12:39 UTC by marwin1991

2022-08-15 12:21 UTC, marwin1991 commented
@angrymeir when you will have some time can you take a look at this change ? :)

2022-09-06 07:59 UTC, marwin1991 commented
@angrymeir

2022-09-19 06:54 UTC, marwin1991 commented
@angrymeir Will you find a time this week to look at this change?

2022-09-22 18:20 UTC, angrymeir requested changes
Wow! This looks super awesome - great work!!! Really, thats some next level shit 🎉

2022-09-24 13:44 UTC, marwin1991 commented on secscanner2junit/sast.py
> +from secscanner2junit.config import Config
@angrymeir is it corrent import?

2022-09-24 13:48 UTC, marwin1991 commented on tests/test_config.py
> +        input_config_path = "resources/test_config/test_get_config_no_file/ss2ju-config.yml"
I have added empty `test_get_config_no_file` dir, and this test is checking if when file does not exist, the program should return empty config

2022-09-24 13:49 UTC, marwin1991 commented on tests/test_config.py
> +        assert expected == config
Yes, you are rigth :)

2022-09-27 07:53 UTC, angrymeir approved these changes

2022-09-27 07:54 UTC, merged